baseURL: "https://charlottecvn.github.io/"
title: Charlotte Cambier van Nooten
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: papers/
          weight: 1
        - name: Talks
          url: talks/
          weight: 2
        - name: Resume
          url: cv_charlotte.pdf
          weight: 3
params:
    description: "I am a PhD Candidate in graph-based machine learning."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Charlotte Cambier van Nooten
          subtitle: "I am a PhD candidate in graph-based machine learning for energy grids at the Radboud University Nijmegen (RU), Alliander, and the AI for Energy Grids lab."
          imageUrl: #"picture.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Charlotte Cambier van Nooten
          buttons:
            - name: Publications
              url: papers/
            # - name: Courses
            #   url: courses/
            # - name: Data
            #   url: data/
           # - name: Newsletter
           #   url: https://pmichaillat.substack.com
            # - name: Tags
            #   url: tags/
            - name: Talks
              url: talks/
            - name: Resume
              url: cv_charlotte.pdf
            #- name: Archive
            #  url: archive/
    socialIcons:
        # - name: CV
        #   url: cv_rosa.pdf
        - name: Email
          url: mailto:charlotte.cambiervannooten@ru.nl
        - name: Location
          url: location/
    
        - name: Google Scholar
          url: https://scholar.google.com/
        - name: LinkedIn
          url: https://linkedin.com/in/charlotecambiervannooten
        - name: GitHub
          url: https://github.com/charlottecvn
        - name: ORCID
          url: https://orcid.org/
      

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Charlotte Cambier van Nooten"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
